db:
  host: 127.0.0.1:3306
  user: root
  password: 123456
  dbname: video

log:
  path: ./video.log

mode: debug

server:
  domain: http://127.0.0.1
  port: 49152
  assets_path: ./assets
  secret: 123456

email:
  user: 985759262@qq.com
  token: