// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/email.proto

package email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Email service

func NewEmailEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Email service

type EmailService interface {
	Send(ctx context.Context, in *RequestEmail, opts ...client.CallOption) (*ResponseEmail, error)
}

type emailService struct {
	c    client.Client
	name string
}

func NewEmailService(name string, c client.Client) EmailService {
	return &emailService{
		c:    c,
		name: name,
	}
}

func (c *emailService) Send(ctx context.Context, in *RequestEmail, opts ...client.CallOption) (*ResponseEmail, error) {
	req := c.c.NewRequest(c.name, "Email.Send", in)
	out := new(ResponseEmail)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Email service

type EmailHandler interface {
	Send(context.Context, *RequestEmail, *ResponseEmail) error
}

func RegisterEmailHandler(s server.Server, hdlr EmailHandler, opts ...server.HandlerOption) error {
	type email interface {
		Send(ctx context.Context, in *RequestEmail, out *ResponseEmail) error
	}
	type Email struct {
		email
	}
	h := &emailHandler{hdlr}
	return s.Handle(s.NewHandler(&Email{h}, opts...))
}

type emailHandler struct {
	EmailHandler
}

func (h *emailHandler) Send(ctx context.Context, in *RequestEmail, out *ResponseEmail) error {
	return h.EmailHandler.Send(ctx, in, out)
}
