// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/video.proto

package video

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Video service

func NewVideoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Video service

type VideoService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Video_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Video_PingPongService, error)
}

type videoService struct {
	c    client.Client
	name string
}

func NewVideoService(name string, c client.Client) VideoService {
	return &videoService{
		c:    c,
		name: name,
	}
}

func (c *videoService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Video.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Video_StreamService, error) {
	req := c.c.NewRequest(c.name, "Video.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &videoServiceStream{stream}, nil
}

type Video_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type videoServiceStream struct {
	stream client.Stream
}

func (x *videoServiceStream) Close() error {
	return x.stream.Close()
}

func (x *videoServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *videoServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *videoServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *videoServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *videoService) PingPong(ctx context.Context, opts ...client.CallOption) (Video_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Video.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &videoServicePingPong{stream}, nil
}

type Video_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type videoServicePingPong struct {
	stream client.Stream
}

func (x *videoServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *videoServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *videoServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *videoServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *videoServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *videoServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Video service

type VideoHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Video_StreamStream) error
	PingPong(context.Context, Video_PingPongStream) error
}

func RegisterVideoHandler(s server.Server, hdlr VideoHandler, opts ...server.HandlerOption) error {
	type video interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Video struct {
		video
	}
	h := &videoHandler{hdlr}
	return s.Handle(s.NewHandler(&Video{h}, opts...))
}

type videoHandler struct {
	VideoHandler
}

func (h *videoHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.VideoHandler.Call(ctx, in, out)
}

func (h *videoHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.VideoHandler.Stream(ctx, m, &videoStreamStream{stream})
}

type Video_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type videoStreamStream struct {
	stream server.Stream
}

func (x *videoStreamStream) Close() error {
	return x.stream.Close()
}

func (x *videoStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *videoStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *videoStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *videoStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *videoHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.VideoHandler.PingPong(ctx, &videoPingPongStream{stream})
}

type Video_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type videoPingPongStream struct {
	stream server.Stream
}

func (x *videoPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *videoPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *videoPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *videoPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *videoPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *videoPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
